package m.schuermann.weiterbildungskatalog;

import org.springframework.boot.builder.SpringApplicationBuilder;

//This class was generated by [spring initializr].
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

public class ServletInitializer extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(WeiterbildungskatalogApplication.class);
	}

}
