package m.schuermann.weiterbildungskatalog;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//This class was generated by [spring initializr].

@SpringBootApplication
public class WeiterbildungskatalogApplication {

	public static void main(String[] args) {
		SpringApplication.run(WeiterbildungskatalogApplication.class, args);
	}

}
